### Insertion of a node in a Linked list at the beginning

In [7]:
class Node :
    def __init__ (self , data):
        self.data = data
        self.nextPtr = None

class LinkedList:
    def __init__(self):
        self.head = None
    
    ## insert the new node at the beginning of the linked list 
    def insertAtbeginning(self , new_data):
        ## Create a new node for the new_data
        new_node = Node(new_data)
        ## insertion at the beginning of the linked list 
        new_node.nextPtr =self.head
        self.head = new_node 
        
    ## print the Linked list 
    def printLinkedList(self):
        temp = self.head
        while temp :
            print(str(temp.data)+" " , end =" ")
            temp = temp.nextPtr
    
## Drivers Code 
llist= LinkedList()
llist.insertAtbeginning(10)
llist.insertAtbeginning(20)
llist.insertAtbeginning(30)
llist.insertAtbeginning(40)
llist.insertAtbeginning(50)
llist.printLinkedList()
    

50  40  30  20  10  

### Insertion of a node in a Linked list at the end


In [23]:
class Node:
    def __init__(self,data):
        self.data= data
        self.nextPtr = None
    
class LinkedList:
    def __init__(self):
        self.head = None
        
## insert the new node at the end of the linked list 
    def insertAtEnd(self, new_data):
        ## create a new node for the new data
        new_node = Node(new_data)
    
    ## Check wether linked list is empty or different     
        if self.head is None:
            self.head = new_node
            return 
    
        ## insert the data at the end 
        temp = self.head
        while temp.nextPtr:
            temp = temp.nextPtr
        
        temp.nextPtr = new_node
        
        
    ## print the linked list
    def printLinkedList(self):
        temp = self.head
        while temp:
            print(str(temp.data)+" " , end =" ")
            temp = temp.nextPtr
    
## Drivers Code 
llist = LinkedList()
llist.insertAtEnd(10)
llist.insertAtEnd(20)
llist.insertAtEnd(30)
llist.insertAtEnd(40)
llist.insertAtEnd(50)
llist.printLinkedList()
    

10  20  30  40  50  

### Insertion of a node in a Linked list after any of the node.


In [1]:
class Node:
    def __init__(self, data):
        self.data = data
        self.nextPtr = None

class LinkedList:
    def __init__(self):
        self.head = None

    # Insert a new node at the end of the linked list
    def insertAtEnd(self, new_data):
        # Create a new node for the new data
        new_node = Node(new_data)

        # Check whether the linked list is empty
        if self.head is None:
            self.head = new_node
            return

        # Insert the new node at the end
        temp = self.head
        while temp.nextPtr:
            temp = temp.nextPtr
        temp.nextPtr = new_node

    # Insert a new node after a given node
    def insertAfterNode(self, prev_node, new_data):
        if prev_node is None:
            print("The given previous node must be in the linked list.")
            return

        # Create a new node and adjust the pointers
        new_node = Node(new_data)
        new_node.nextPtr = prev_node.nextPtr
        prev_node.nextPtr = new_node

    # Print the linked list
    def printLinkedList(self):
        temp = self.head
        while temp:
            print(str(temp.data) + " ", end=" ")
            temp = temp.nextPtr

# Driver code
if __name__ == "__main__":
    llist = LinkedList()

    llist.insertAtEnd(10)
    llist.insertAtEnd(20)
    llist.insertAtEnd(30)
    llist.insertAtEnd(40)
    llist.insertAtEnd(50)
    print('Insertion of nodes at the end of the linked list:')
    llist.printLinkedList()
    print()
    print("Insertion of a node after the second node of the linked list:")
    llist.insertAfterNode(llist.head.nextPtr, 25)
    llist.printLinkedList()


Insertion of nodes at the end of the linked list:
10  20  30  40  50  
Insertion of a node after the second node of the linked list:
10  20  25  30  40  50  

In [4]:
## Implementation of Strassens's matrix multiplication
## Recurrence relation : 7T(n/2) +n^2
## Using master's theorem , O(n^22.81)
## Approach - using divide and conquer 
import numpy as np 

def split(matrix):
    row, col = matrix.shape 
    row2 , col2 = row//2 , col //2
    return matrix[:row2, :col2], matrix[:row2, col2:], matrix[row2:, :col2], matrix[row2:, col2:]

def strassen(x , y):
    ## Base case when size of matrix is 1X1
    if len(x)==1:
        return x * y 
    
    ## Splitting the matrices into quadrants . This will be done recursively 
    ## until the base case is related . 
    a , b , c ,d = split(x)
    e , f ,g, h = split(y)
    
    ## computing the 7 products , recursively (p1 , p2 ..p7)
    p1 = strassen(a, f-h)
    p2 = strassen(a+b , h)
    p3 = strassen(c+d ,e)
    p4 = strassen(d , g -e)
    p5 = strassen(a+d , e+h)
    p6 = strassen(b - d , g+h )
    p7 =strassen(a -c , e+f)

    ## Computing the values of the 4 quadrants of the final matrix c 
    c11 = p5 +p4 -p2 +p6
    c12 = p1 +p2 
    c21 = p3 + p4
    c22 = p1 +p5 -p3 -p7

    ## Combining the 4 quadrants into a single matrix by stacking horizontally and vertically 
    
    c = np.vstack((np.hstack((c11 ,c12 )) , np.hstack((c21 , c22))))
    return c 
## Drivers Code 
A = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[2,2,2,2,]])
B = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[2,2,2,2,]])
print('Matrix multiplication result:')
print(strassen(A,B))

Matrix multiplication result:
[[ 8  8  8  8]
 [16 16 16 16]
 [24 24 24 24]
 [16 16 16 16]]


In [8]:
## Power of an element
def myPow(x ,n ):
    if n == 0:
        return 1 
    elif n < 0:
        x = 1/x
        n = -n
        return myPow(x , n)
    elif n ==1:
        return x 
    else :
        ## Divide
        mid = n//2
        ## conquer
        b = myPow(x , mid )
        
        result = b* b
        ## Combine
        if n% 2 == 0 :
            return result 
        else :
            return result * x 
## Drivers Code
x = 2.00000
n = -2
result = myPow(x , n)
print(result)

0.25


### Divide two numbers without using division , multiplication and modulo operator 

In [1]:
## Method definition 
def divide(dividend , divisor ):
    divid = abs(dividend)
    div = abs(divisor)
    result = 0 

    while divid >= div :
        shift = 0 
    ## left shift operator 
        while divid >=(div << shift):
            shift += 1 
        
            result +=(1 << (shift - 1))
            divid -= div <<(shift -1)
        ## negative case handling 
        if (dividend < 0 and divisor >=0 ) or (divisor < 0 and dividend >= 0):
            result = -result 
    return min(2147483647 , max(-2147483648 , result))

## Drivers Code 
dividend = 47
divisor = 4
result = divide(dividend , divisor)
print(result)
    

11


## Reversal in a  linked list 


In [13]:
class Node :
    def __init__(self, data):
        self.data = data 
        self.nextPtr = None 

class LinkedList:
    def __init__(self):
        self.head = None 
        
        ## Insert the new node at the end of the linked list 
    def insertAtEnd(self,new_data):
        ## Create a new node for the new data 
        new_node = Node(new_data)
            
        ## Check whether linked list is empty or different 
        if self.head is None:
            self.head = new_node 
            return 
    
        ## insert the data at the end 
        temp = self.head 
        while temp.nextPtr:
            temp = temp.nextPtr 
        
        temp.nextPtr = new_node 
        
    ## Print the linked list 
    def printLinkedList(self):
        temp = self.head
        while temp :
            print(str(temp.data)+ " " , end = " " )
            temp = temp.nextPtr 
        print() ## For new line after printing the list 
        

## To reverse a linked list 
    def reverseList(self):
        prev = None 
        curr = self.head 
        while curr :
            next = curr.nextPtr 
            curr.nextPtr = prev 
            prev = curr 
            curr = next 
    ## update the head pointer 
        self.head = prev 

## Drivers Code 
llist=LinkedList()

llist.insertAtEnd(10)
llist.insertAtEnd(20)
llist.insertAtEnd(30)
llist.insertAtEnd(40)
llist.insertAtEnd(50)
llist.printLinkedList()

llist.reverseList()
print("Reversal of the linked list :")
llist.printLinkedList()

10  20  30  40  50  
Reversal of the linked list :
50  40  30  20  10  


## Floyds cycle detection algorithm - Two pointer





In [25]:
class Node:
    def __init__(self,data):
        self.data= data
        self.nextPtr = None
    
class LinkedList:
    def __init__(self):
        self.head = None
        
## insert the new node at the end of the linked list 
    def insertAtEnd(self, new_data):
        ## create a new node for the new data
        new_node = Node(new_data)
    
    ## Check wether linked list is empty or different     
        if self.head is None:
            self.head = new_node
            return 
    
        ## insert the data at the end 
        temp = self.head
        while temp.nextPtr:
            temp = temp.nextPtr
        
        temp.nextPtr = new_node
        
    ## To detect the loop inside a linked list 
    def detectloop(self):
        hare = self.head
        tortoise = self.head
        
        while tortoise and hare and hare.nextPtr:
            hare = hare.nextPtr.nextPtr
            tortoise  = tortoise.nextPtr 
            
            if tortoise == hare :
                return True 
        return False
        
        
        
    ## print the linked list
    def printLinkedList(self):
        temp = self.head
        while temp:
            print(str(temp.data)+" " , end =" ")
            temp = temp.nextPtr
    
## Drivers Code 
llist = LinkedList()
llist.insertAtEnd(10)
llist.insertAtEnd(20)
llist.insertAtEnd(30)
llist.insertAtEnd(40)
llist.insertAtEnd(50)

## Make a loop inside a linked list 
llist.head.nextPtr.nextPtr.nextPtr = llist.head
if llist.detectloop():
    print("loop is inside the linked list ")
else:
    print("No Loop ")

loop is inside the linked list 


## 1. Deletion of the linked list 

In [34]:
class Node:
    def __init__(self, data):
        self.data = data
        self.nextPtr = None
        
class LinkedList:
    def __init__(self):
        self.head = None
        
    # Insert a new node at the end of the linked list 
    def insertAtEnd(self, new_data):
        # Create a new node with the provided data 
        new_node = Node(new_data)
        
        # Check whether the linked list is empty 
        if self.head is None:
            self.head = new_node 
            return 
        
        # Traverse to the end of the list and insert the new node 
        temp = self.head 
        while temp.nextPtr:
            temp = temp.nextPtr 
        temp.nextPtr = new_node
        
    # Delete the node at a given position 
    def deleteNode(self, pos):
        if self.head is None:
            return 

        temp = self.head
        
        # If head needs to be removed
        if pos == 0:
            self.head = temp.nextPtr
            temp = None
            return
        
        # Find the node before the node to be deleted
        for i in range(pos - 1):
            temp = temp.nextPtr
            if temp is None or temp.nextPtr is None:
                return
        
        # Node temp.nextPtr is the node to be deleted
        nextPtr = temp.nextPtr.nextPtr
        temp.nextPtr = None
        temp.nextPtr = nextPtr
        
    # Print the linked list 
    def printLinkedList(self):
        temp = self.head
        while temp:
            print(str(temp.data) + " ", end=" ")
            temp = temp.nextPtr 
        print()
        
# Driver Code
llist = LinkedList()
llist.insertAtEnd(10)
llist.insertAtEnd(20)
llist.insertAtEnd(30)
llist.insertAtEnd(40)
llist.insertAtEnd(50)
print("Insertion of nodes at the end of the linked list")

llist.printLinkedList()
print()
print("Deletion of nodes of the linked list")

llist.deleteNode(3)
llist.printLinkedList()
print()
llist.deleteNode(2)
llist.printLinkedList()
print()
llist.deleteNode(1)
llist.printLinkedList()
print()
llist.deleteNode(1)
llist.printLinkedList()
print()
llist.deleteNode(0)
llist.printLinkedList()
print()


Insertion of nodes at the end of the linked list
10  20  30  40  50  

Deletion of nodes of the linked list
10  20  30  50  

10  20  50  

10  50  

10  





## 2. Count number of nodes of the linked list 


In [2]:
class Node :
    def __init__(self , data):
        self.data = data 
        self.nextPtr = None 
class LinkedList:
    def __init__(self):
        self.head = None 
        
    ## insert the new node at the end of the linked list 
    def insertAtEnd(self, new_data):
        ## Create a new node for the new data 
        new_node = Node(new_data)
        
        ## Check whether Linked list is empty or different 
        if self.head is None:
            self.head = new_node
            return 
        ## insert the data at the end 
        
        temp = self.head 
        while temp.nextPtr:
            temp = temp.nextPtr 
            
        temp.nextPtr = new_node 
        
    ## Count the number of nodes in the linkes list 
    def countNodes(self):
        temp = self.head
        count= 0 
        while temp :
            count += 1
            temp = temp.nextPtr 
        return count    
        
        
        
    ## print the linked list 
    def printLinkedList(self):
        temp = self.head 
        while temp:
            print(str(temp.data)+" " , end = " ")
            temp = temp.nextPtr 

## Drivers Code 
llist = LinkedList()

llist.insertAtEnd(10)
llist.insertAtEnd(20)
llist.insertAtEnd(30)
llist.insertAtEnd(40)
llist.insertAtEnd(50)
print("Insertion of nodes at the end of the linked list :")
llist.printLinkedList()
print()

result = llist.countNodes()
print("Count of number of nodes in the given Linked List " , result )

Insertion of nodes at the end of the linked list :
10  20  30  40  50  
Count of number of nodes in the given Linked List  5


## 3. Search a Node in a given linked list 

In [17]:
class Node :
    def __init__(self , data):
        self.data = data 
        self.nextPtr = None
        
class LinkedList:
    def __init__(self):
        self.head = None
    
    ## insert the new node at the end of the linked list 
    def insertAtEnd(self , new_data):
        ## Create a new node for the new data
        new_node = Node(new_data)
        
        ## Check wether linked list is empty or different 
        if self.head is None :
            self.head= new_node 
            return 
    
    ## insert the data at the end 
        temp = self.head
        while temp.nextPtr :
            temp = temp.nextPtr
        temp.nextPtr = new_node 
    
## Search for a given node inside the linked list
## If the node is present return True otherwise return False
    def searchNode(self , nodeData):
        ## Write your code 
        temp = self.head
        while temp: 
            if temp.data == nodeData:
                return True 
            temp= temp.nextPtr
        
        return False

         ## Print the linked list 
    def printLinkedList(self):
        temp = self.head
        while temp :
            print(str(temp.data)+ " " , end = " ")
            temp = temp.nextPtr 
        print()
## Drivers Code 
llist = LinkedList()
llist.insertAtEnd(10)
llist.insertAtEnd(20)
llist.insertAtEnd(30)
llist.insertAtEnd(40)
llist.insertAtEnd(50)
print("Insertion of nodes at the end of the linked list :")
llist.printLinkedList()
print()

nodeData = 90 
if llist.searchNode(nodeData):
    print("Data is present inside the linked list")
else:
    print("No Data present inside the linked list ")

Insertion of nodes at the end of the linked list :
10  20  30  40  50  

No Data present inside the linked list 


## 4. Merge two sorted linked list and give me the final sorted version of the linked list .

In [24]:
class Node:
    def __init__(self, data):
        self.data = data
        self.nextPtr = None

class LinkedList:
    def __init__(self):
        self.head = None

    # Insert a new node at the end of the linked list
    def insertAtEnd(self, new_data):
        # Create a new node with the provided data
        new_node = Node(new_data)
        
        # Check whether the linked list is empty
        if self.head is None:
            self.head = new_node
            return
        
        # Traverse to the end of the list and insert the new node
        temp = self.head
        while temp.nextPtr:
            temp = temp.nextPtr
        temp.nextPtr = new_node

    # Merge two sorted linked lists
    @staticmethod
    def mergeLists(head1, head2):
        if head1 is None:
            return head2
        
        if head2 is None:
            return head1
        
        if head1.data <= head2.data:
            temp = head1
            temp.nextPtr = LinkedList.mergeLists(head1.nextPtr, head2)
        else:
            temp = head2
            temp.nextPtr = LinkedList.mergeLists(head1, head2.nextPtr)
        
        return temp

    # Print the linked list
    def printLinkedList(self):
        temp = self.head
        while temp:
            print(str(temp.data) + " ", end=" ")
            temp = temp.nextPtr
        print()

# Driver Code
llist1 = LinkedList()
llist2 = LinkedList()

llist1.insertAtEnd(10)
llist1.insertAtEnd(20)
llist1.insertAtEnd(30)
llist1.insertAtEnd(40)
llist1.insertAtEnd(50)
print("Insertion of nodes at the end of the 1st linked list:")
llist1.printLinkedList()
print()

llist2.insertAtEnd(11)
llist2.insertAtEnd(22)
llist2.insertAtEnd(33)
llist2.insertAtEnd(44)
llist2.insertAtEnd(55)
print("Insertion of nodes at the end of the 2nd linked list:")
llist2.printLinkedList()
print()

llist3 = LinkedList()
llist3.head = LinkedList.mergeLists(llist1.head, llist2.head)
print("Merged linked list:")
llist3.printLinkedList()


Insertion of nodes at the end of the 1st linked list:
10  20  30  40  50  

Insertion of nodes at the end of the 2nd linked list:
11  22  33  44  55  

Merged linked list:
10  11  20  22  30  33  40  44  50  55  
